### ISSUE TITLE
Downloading data within range of dates

### ISSUE THREAD

**Issue by zmonteith** [HakaiInstitute/hakai-api-client-r#1]
When I try to download seagrass data between dates (ie . `sgEndpoint = sprintf("%s/%s", client$api_root, 
"eims/views/output/mg_seagrass_habitat?date>=2016-01-01&date<2019-01-01")` ), only a subset of the data (20 of 667 records) is loaded. 

If instead I try to load the last 1000 records (ie. `sgEndpoint = sprintf("%s/%s", client$api_root,
                     "eims/views/output/mg_seagrass_habitat?limit=1000")`), all the records work.

Am I misunderstanding how to use this function, or is this a bug?

Thanks!

**Comment by finnshort** [comment]
Hi Zach, this is the intended behaviour.  The default limit is 20 to prevent users from accidentally returning a huge number of results from their query.  It's in the tl;dr of the simplified API documentation [here](https://github.com/HakaiInstitute/hakai-api/blob/master/docs/simplified-api-documentation.md), or you can read the full query docs [here](https://github.com/HakaiInstitute/hakai-api/blob/master/docs/querying-data.md).  Let me know if you have any follow up questions!

**Comment by zmonteith** [comment]
Awesome thanks Finn. I must have missed that, but I see it now!
