### ISSUE TITLE
Can't open a connection with api

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/hakai-api-client-r#16]
When I run `client <- hakaiApi::Client$new()` and log in using the browser to receive my key and then paste the key into R I get the following error:

`Error in file(private$credentials_file, "w") : cannot open the connection
In addition: Warning message:
In file(private$credentials_file, "w") :
  cannot open file '/Users/pkgbuild/.hakai-api-auth-r': No such file or directory`

I'm using the version of this package downloaded from CRAN on R version 4.0.5 (2021-03-31) on Mac OS

**Comment by tayden** [comment]
Hey @Br-Johnson, is this the first time you tried the CRAN version? Does installing from github resolve the issue?

**Comment by tayden** [comment]
I suspect the Github version will work. I think I know what the issue is.

**Comment by Br-Johnson** [comment]
Yes, the github version works!
